apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-r5kk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-r5kk
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-r5kk
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-r5kk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-r5kk
    spec:
      containers:
      - image: quay.io/qijing/push-pyxis-nsld-tenant/appstudio/dc-metro-map-r5kk@sha256:2cee58570dd14d310275a56e07c1a7502524896aad984219430efb825e03b421
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
